### ISSUE TITLE
v0.4

### ISSUE THREAD

**Issue by wildsm** [bandframework/bandframework#110]
This is an issue that will be updated to reflect things targeted for a v0.4.0 release. This posting will be updated based on the conversation that follows. Please include others who were not included thus far.

Pull requests should be submitted to the `develop` branch.

We are looking volunteers to review pull requests over the next month.

**Changes slated for review/release beyond current v0.3**

Existing tools and examples:

- [x] surmise will be updated to [surmise v0.3](https://github.com/bandframework/surmise/pull/121); see #125 

- [x] SaMBA - @asemposki updated to v1.1.0, includes new documentation (#118)

- [x] parMOO  - updated to [ParMOO v0.4.1](https://github.com/parmoo/parmoo/tree/release/v0.4.1) @wildsm @thchang (#117)

- [x] rose will be updated to v1.1.3; see #123 

- [x] BMEX is staying as is

- [x] Taweret updated to version v1.1.0 
 
- [x] Bfrescox  

  - @ozgesurer will check that everything still working after surmise is updated. 
  - Should this be in software or examples?

- BRICK -- per @DanielRPhillips, staying as and where is.

- QGP_Bayes -- staying as is @danOSU  ? Everything still working? Move to examples?

Potential new things:

- [x] Smooth emulator added via #72 

- [x] Nuclear saturation -- @cdrischler  [branch](https://github.com/bandframework/bandframework/tree/v04/christian) is ready for testing; see #124 

- [x] jitr added via PR #103

- [x] PUQ -@ozgesurer added [PUQ v.0.1.0](https://github.com/parallelUQ/PUQ)  (#119)

Documentation, infrastructure, open issues:

- [x] Unfortunately `main` was ahead of `develop` right now. Still need to address #104 and #106. These have now been addressed!

- Open issues not noted above are #20 and #23.

- Did some overall cleanup (#121 , #116 , #115, #111 )

What else?

**Comment by mosesyhc** [comment]
@wildsm @ozgesurer : Let me know if you would like me to test PUQ.

**Comment by mosesyhc** [comment]
@wildsm: Kyle Beyer is not listed as a member of the BAND organization. Potentially the issue you couldn't tag him?

**Comment by wildsm** [comment]
@beykyle has been invited to be a member of https://github.com/orgs/bandframework/teams/band-contributors

Thanks @mosesyhc

**Comment by jared321** [comment]
> Taweret: We will definitely have a new version release with Read the Docs documentation and the more pedagogical Jupyter Book, both of which are building and very close to completion. @jared321, are we also including the new `meson` build structure in v0.4?

@asemposki I would prefer to officially integrate `meson`-based builds as part of an official release of OpenBTMixing so that we can make certain that everything is working together appropriately with loads of testing.  A possibly good time for this would be when John officially integrates his changes to the OpenBTMixing/Taweret interface.

This implies that for this release Taweret users would still install the openbtmixing Python package available in PyPI, which requires a pre-installation of OpenMPI.  Acceptable?

**Comment by asemposki** [comment]
@jared321 That sounds fine with me for this release. If I recall correctly from discussions with the other BAND members, we could always do a smaller bandframework release somewhere between now and next year, if desired, and if there is enough to include.

**Comment by asemposki** [comment]
@cdrischler, @mosesyhc: If you need a reviewer to test code, let me know!

**Comment by asemposki** [comment]
In response about SAMBA, I have finally gotten the API to build, and I will finish the documentation edits by the end of the week, so the documentation will be ready to go into v0.4.

**Comment by kylegodbey** [comment]
Unless @beykyle protests, v1.1.3 of rose will be the version

**Comment by asemposki** [comment]
I have updated SAMBA's documentation so it is now fully documented, and I have updated the SDK to v0.4, so we are ready there for including the new version in v0.4. The number will be v1.1.0.

**Comment by asemposki** [comment]
In keeping with our version numbering, Taweret is set to be v1.1.0; @jared321 feel free to object if you wish.

**Comment by wildsm** [comment]
September 9 update:
- See changes currently staged for next version at https://github.com/bandframework/bandframework/compare/main...develop
- Note in particular the [CHANGELOG](https://github.com/bandframework/bandframework/blob/develop/CHANGELOG.rst)
- parmoo, PUQ, SAMBA have all made it to `develop`

**Comment by cdrischler** [comment]
`nuclear_saturation` is ready for testing and integration into the BAND framework v0.4. The repo already contains the SDK document. What are the next steps?

**Comment by asemposki** [comment]
@cdrischler PR into `develop` of this repo, and one of us will review and test the code. :)

**Comment by ozgesurer** [comment]
@wildsm Report on bfrescox:

- I ran two examples provided for Tutorial I (python3 example_surmise1.py and python3 example_surmise2.py) with surmise 0.3.0, and they ran successfully.

- I encountered issues with the Colab documents (from 2021 BAND Camp). I fixed most problems by changing the git clone command to `git clone https://github.com/bandframework/bandframework/`. However, I couldn't resolve the issue with the third Colab that uses `ptemcee`. After spending a couple of hours on it, it appears the package is not maintained and is incompatible with newer versions of Python. I added a warning at the beginning of this section to inform users.

- Overall, I think bfrescox will remain as it is.

**Comment by DanielRPhillips** [comment]
Thanks @ozgesurer. One of my students resolved issues with ptemcee and recent python implementation by changing all instances (only a few I believe) of np.float in the source code to just float. But I am also fine with solution you have implemented.

**Comment by mosesyhc** [comment]
@ozgesurer, @DanielRPhillips : In the effort of updating surmise, the same issue with `ptemcee` also occurs.  It is good to know that there is a patch, but it may be a hotfix since anyone trying to pip install ptemcee may run into an issue.

For the original `Bfrescox_GPR` tutorial, the purpose seems to be showing a basic example of sampling, in which `ptemcee` is not the only choice.  I gave a modification of the colab notebook to use `emcee` instead.  If this seems like a good solution, we may redirect that colab notebook link to the following and not lose any part of the original BFresco: https://colab.research.google.com/drive/1vYNIVVXcPhJSjgmMAIbOyeg17pGFPDyh?usp=sharing

**Comment by ozgesurer** [comment]
@DanielRPhillips If you have a link to your student's repo, we can point it out from the colab as well.

@mosesyhc Thanks for the update. I am OK with changing existing link with the one your provided. Or we can provide another link from the bandframework (as alternative to this Colab document) referring you and your link.

**Comment by mosesyhc** [comment]
@ozgesurer Either way works for me! I made very minimal changes to make it work.

**Comment by DanielRPhillips** [comment]
@moseshyc: I agree. ptemcee is not needed for basic MCMC sampling. Let's redirect to your colab notebook modification and use emcee instead. More physicists are familiar with emcee anyway, for exactly the reason you say. 

Did you do the ptemcee->emcee fix for surmise? Or are you waiting for a better solution?

**Comment by DanielRPhillips** [comment]
@ozgesurer: Here is Andrius' repo: https://github.com/AndriusBurn/3he_alpha_mc_sampling. He said "The relevant edits were "np.float" -> "float" made on lines (261, 262, 264, 265, 432, 434) of venv/lib/python3.12/site-packages/ptemcee/sampler.py".

**Comment by ozgesurer** [comment]
@DanielRPhillips @mosesyhc Thanks for the feedback. The updated Colab notebook can be found at [Section III-Tutorial I](https://colab.research.google.com/drive/1rtHiu-f8hy0ICw8WscjLqWdDHvCtBoMb?usp=sharing#scrollTo=sptJ4wT2A6bY)

I included the following warning at the beginning. Daniel, from my understanding, Andrius' repo contains other files as well so I was not able to link directly it. Instead, I provided instructions to demonstrate how to fix the source code of `ptemcee` within the Colab environment. It’s currently running smoothly.

WARNING (September 2024): The Python package ptemcee appears to be largely inactive, with no updates or releases in several years (last release was around 9 years ago). Recent discussions indicate that it may not be compatible with newer versions of Python due to the use of deprecated APIs, such as older NumPy functions.

The following example may not run properly with Python versions 3.9 and later. If you require compatibility with newer Python or NumPy versions, forking the repository and updating it yourself may be the best option.

**We suggest two alternatives:**

1) **Switch to emcee**: Our BAND member Moses Chan (Northwestern) replaced the ptemcee with the emcee package. [See the running example with the emcee package.](https://colab.research.google.com/drive/1vYNIVVXcPhJSjgmMAIbOyeg17pGFPDyh?usp=sharing)

2) **Fix ptemcee**: The following example shows how to modify ptemcee's source code to ensure compatibility with newer versions of NumPy. The instructions are provided by Andrius Burn (Ohio).

**Comment by DanielRPhillips** [comment]
I like it! Thank you both for taking care of this.

**Comment by mosesyhc** [comment]
> @mosesyhc : I agree. ptemcee is not needed for basic MCMC sampling. Let's redirect to your colab notebook modification and use emcee instead. More physicists are familiar with emcee anyway, for exactly the reason you say.
> 
> Did you do the ptemcee->emcee fix for surmise? Or are you waiting for a better solution?

For surmise, the method depending on `ptemcee` is removed in the last release. This will get a fix when we consider outsourcing the sampling methods in the upcoming year. But it doesn't stop anyone to use surmise, or surmise + emcee if they wish to utilize other sampling methods.

**Comment by mosesyhc** [comment]
Review for including surmise v0.3.0 is complete, merged into develop.

**Comment by wildsm** [comment]
rose is also in.

I believe only the following are outstanding:
- Taweret will be updated to version v1.1.0 @jared321 @ominusliticus @asemposki @jcyannotty et al; Draft PR in progress; see #130 

- BRICK -- staying as is @odell @DanielRPhillips  ? Everything still working? Should this be in software or examples (see #114)?

- QGP_Bayes -- staying as is @danOSU  ? Everything still working?

- Smooth emulator -- @scottedwardpratt [branch](https://github.com/bandframework/bandframework/tree/v03/smoothemulatorscott) is ready for testing @kylegodbey for #72 

- jitr-- @beykyle  -where do things stand with #103?

**Comment by asemposki** [comment]
We will have the PR draft turned into a real PR in a couple days at most. Finishing some cleaning up of the PyPI deployment currently.

**Comment by DanielRPhillips** [comment]
James de Boer says that there has been no implementation of new functionality in BRICK since the v0.3 release. BRICK is also stable in that he is not aware of issues in that version, either from his own work or from issues raised by the growing BRICK user community. 

Since BRICK is being adopted as a software tool I would favour it staying in the software portion of the repo.

**Comment by asemposki** [comment]
@wildsm Concerning the MIT License, should we change the copyright date in it to reflect all release years, or keep it as the initial copyright of 2022? This is our last question before I open the PR for Taweret.

**Comment by wildsm** [comment]
> @wildsm Concerning the MIT License, should we change the copyright date in it to reflect all release years, or keep it as the initial copyright of 2022? This is our last question before I open the PR for Taweret (tomorrow morning at the latest).

Some people are against including multiple dates in copyrights (first search link I found was https://nexb.com/do-you-really-need-to-update-the-copyright-each-new-year), so I think you can do as you like (I would still keep the first year, fwiw)

**Comment by asemposki** [comment]
@beykyle Can somebody with a MacOS test `jitr`? I could test it within the next 2 days. 

@wildsm We'll have our PR open by the evening, once @jared321 tests our binary wheel for Linux from PyPI.

**Comment by asemposki** [comment]
The Taweret PR is now open!

**Comment by wildsm** [comment]
From the above checklist, it sounds like the software and example additions for v0.4 are now complete, meaning that everything that is staged for v0.4 has now been merged to the `develop` branch.

What remains is to go through the release process and get everything ready for the formal release process (#131 ?), probably targeting a September 30, 2024 release date. 

In the meantime it would be awesome for people to take a look at #131 and the `develop` branch overall so as to make changes to the `v04/documentation` branch intended to capture things missing from `develop` (see #138).

One of these things is related to updating the [AUTHORS](https://github.com/bandframework/bandframework/blob/v04/documentation/AUTHORS) and propagating this change throughout. Per [CONTRIBUTING](https://github.com/bandframework/bandframework/blob/v04/documentation/CONTRIBUTING.rst), the leads on all new additions have been contacted by the Design & Oversight (D&O) committee to confirm whether they will be listed as authors of v0.4 and whether there are others to be added. If anyone has suggestions for changes to the AUTHORS list from v0.3 to v0.4, please post here or email me (for the D&O) by the end of this week.

**Comment by wildsm** [comment]
Release published: https://github.com/bandframework/bandframework/releases/tag/v0.4.0

These are the remaining post-release items from #131 

- [x]  Update website to reflect existence of new release.

- [x]  Disseminate news of new release to: FRIB-TA mailing list, JETSCAPE/X-SCAPE mailing list, other interested parties.

After those are done, we can close this issues @DanielRPhillips

**Comment by DanielRPhillips** [comment]
The website is now updated and the mailing lists have been mailed. Closing the issue.
